### ISSUE TITLE
Default username and password for jasonbean/guacamole?

### ISSUE THREAD

**Issue by hwwilliams** [jason-bean/docker-templates#1]
You list it as being

- Username: guacadmin
- Password: guacadmin

But that doesnt work for me.

**Comment by jason-bean** [comment]
After a first run that should work as long as you have the variable OPT_MYSQL set to Y.

Have you previously run this Docker?

**Comment by hwwilliams** [comment]
@jason-bean

No I haven't run it before. I'm also using docker compose.

By variable do you mean environment (-e) option?

**Comment by jason-bean** [comment]
Yes, I believe so. Since you are posting this under my Docker templates for unRAID I assumed you were using unRAID. Since it appears you are not using unRAID you also need to set the OPT_LDAP, OPT_DUO, and OPT_CAS variables to "N" unless you plan on using those features.

**Comment by hwwilliams** [comment]
Awesome, tyvm. You might wanna add that info to the [docker hub page for the image](https://hub.docker.com/r/jasonbean/guacamole/). Might be helpful for people like me who don't know any better.

And yea I posted here because I couldn't post an issue on your docker-guacamole github repo page for some reason, and I couldn't find any other way to contact you.
